### ISSUE TITLE
Sequence Diagram

### ISSUE THREAD

**Issue by jackson-wells** [OSU-CS361-W17/group5_project3#1]
communication between front-end & back-end

**Comment by priyankb** [comment]
![16923373_1377055205648761_312862634_n](https://cloud.githubusercontent.com/assets/12078339/23241503/36e7614e-f928-11e6-8872-22d103bcc91b.jpg)

VERY ROUGH VERSION

**Comment by jackson-wells** [comment]
Looks good so far. I think the game is terminated by the server so the arrow would go from server to user

**Comment by stribyw** [comment]
I'm pretty sure that the verification of coordinates is not implemented for placing ships. The verification for firing is confusing to me.
